BonaForMe/BonaForMe.UI/Controllers/AdminController.cs
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.AdminService;
using BonaForMe.ServiceCore.ReportService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace BonaForMe.UI.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IReportService _reportService;
        public AdminController(IAdminService adminService, IReportService reportService)
        {
            _adminService = adminService;
            _reportService = reportService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Dashboard()
        {
            var result = _adminService.GetDashboardData();
            var successInfo = TempData["Success"];
            if (successInfo != null)
            {
                ViewBag.Success = successInfo;
            }
            return View(result.Data);
        }

        [AllowAnonymous]
        public IActionResult Reports()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult GetSalesValue(ReportDateDto reportDateDto)
        {
            try
            {
                var result = _reportService.GetSalesValue(reportDateDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        public FileResult CreateReport(ReportDateDto reportDateDto)
        {
            var result = _reportService.CreateReport(reportDateDto);
            var fileName = reportDateDto.StartDate.ToString() + " - " + reportDateDto.EndDate.ToString();
            return File(result.Data, "application/octet-stream", fileName + ".xlsx");
        }

        public FileResult CreatePDFReport(ReportDateDto reportDateDto)
        {
            var result = _reportService.ReportValue(reportDateDto).Data;

            using (MemoryStream stream = new MemoryStream())
            {
                Document document = new Document();
                document.DefaultPageSetup.RightMargin = 30;
                document.DefaultPageSetup.LeftMargin = 30;

                Section section = document.AddSection();

                Style style = document.Styles["Normal"];
                style.Font.Name = "Verdana";

                Style titleStyle = document.Styles.AddStyle("Title", "Normal");
                titleStyle.Font.Size = 12;
                titleStyle.Font.Color = Colors.LightGray;
                titleStyle.ParagraphFormat.SpaceBefore = 50;
                titleStyle.ParagraphFormat.SpaceAfter = 5;

                style = document.Styles.AddStyle("Content", "Normal");
                style.ParagraphFormat.SpaceAfter = 15;
                style.Font.Color = Colors.Black;
                style.ParagraphFormat.AddTabStop("18cm", TabAlignment.Right);

                style = document.Styles.AddStyle("Content3", "Normal");
                style.ParagraphFormat.SpaceAfter = 15;
                style.Font.Color = Colors.Black;
                style.ParagraphFormat.AddTabStop("10cm", TabAlignment.Right);
                style.ParagraphFormat.AddTabStop("18cm", TabAlignment.Right);

                style = document.Styles.AddStyle("PageTitle", "Normal");
                style.ParagraphFormat.SpaceAfter = 20;
                style.Font.Color = Colors.Black;
                style.Font.Size = 14;

                var culture = new CultureInfo("en");

                section.Add(CreatePageTitle("SOLMAZ LTD."));
                section.Add(Add2Columns("Merchant-ID MCRP24NZ", ((DateTime)reportDateDto.StartDate).ToString("dd MMMM yyyy HH:mm", culture) + "->" + ((DateTime)reportDateDto.EndDate).ToString("dd MMMM yyyy HH:mm", culture)));
                section.Add(Add2Columns("VAT-ID     3933414LH", ""));

                RevenueTaxSummary(section, result.RevenueTaxSummary);
                Taxes(section, result.Taxes);
                RevenueByCategory(section, result.RevenueByCategories);
                RevenueByEmployee(section, result.RevenueByEmployees);
                PaymentMethods(section, result.PaymentMethods);

                PdfDocumentRenderer renderer = new PdfDocumentRenderer(true);
                renderer.Document = document;
                renderer.RenderDocument();
                renderer.PdfDocument.Save(stream, true);

                var fileName = reportDateDto.StartDate.ToString() + " - " + reportDateDto.EndDate.ToString();
                return File(stream.ToArray(), "application/octet-stream", fileName  + ".pdf");
            }
        }

        private void RevenueTaxSummary(Section section, ReportColumnDto revenueTaxSummary)
        {
            Paragraph paragraph = section.AddParagraph();
            paragraph.Style = "Title";
            paragraph.AddText("Revenue and tax summary");
            paragraph.AddSpace(20);
            paragraph.AddText("Number of transactions");
            paragraph.AddSpace(20);
            paragraph.AddText("Amount");

            paragraph.Format.Borders.Bottom = new Border { Width = 1, Color = Colors.LightGray };
            paragraph.Format.Borders.DistanceFromTop = 3;
            section.Add(Add3Columns(revenueTaxSummary.FirstColumn, revenueTaxSummary.SecondColumn, revenueTaxSummary.ThirdColumn));
        }

        private void Taxes(Section section, List<ReportColumnDto> taxes)
        {
            section.Add(CreateTitle("Taxes"));
            foreach (var tax in taxes)
            {
                section.Add(Add2Columns(tax.FirstColumn, tax.SecondColumn));
            }
        }

        private void RevenueByCategory(Section section, List<ReportColumnDto> revenueByCategories)
        {
            section.Add(CreateTitle("Revenue by category (gross)"));
            foreach (var category in revenueByCategories)
            {
                section.Add(Add3Columns(category.FirstColumn, category.SecondColumn, category.ThirdColumn));
            }
        }

        private void RevenueByEmployee(Section section, List<ReportColumnDto> revenueByEmployees)
        {
            section.Add(CreateTitle("Revenue by employee"));
            foreach (var employee in revenueByEmployees)
            {
                section.Add(Add3Columns(employee.FirstColumn, employee.SecondColumn, employee.ThirdColumn));
            }
        }

        private void PaymentMethods(Section section, List<ReportColumnDto> paymentMethods)
        {
            section.Add(CreateTitle("Sales revenue per payment method (gross)"));
            foreach (var method in paymentMethods)
            {
                section.Add(Add3Columns(method.FirstColumn, method.SecondColumn, method.ThirdColumn));
            }
        }

        private Paragraph CreatePageTitle(string text)
        {
            Paragraph paragraph = new Paragraph();
            paragraph.Style = "PageTitle";
            paragraph.AddFormattedText(text, TextFormat.Bold);
            return paragraph;
        }

        private Paragraph CreateTitle(string text)
        {
            Paragraph paragraph = new Paragraph();
            paragraph.Style = "Title";
            paragraph.AddText(text);
            paragraph.Format.Borders.Bottom = new Border { Width = 1, Color = Colors.LightGray };
            paragraph.Format.Borders.Distance = 3;
            return paragraph;
        }

        private Paragraph Add2Columns(string text1, string text2)
        {
            Paragraph paragraph = new Paragraph();
            paragraph.Style = "Content";
            paragraph.AddText(text1);
            paragraph.AddTab();
            paragraph.AddText(text2);
            return paragraph;
        }

        private Paragraph Add3Columns(string text1, string text2, string text3)
        {
            Paragraph paragraph = new Paragraph();
            paragraph.Style = "Content3";
            paragraph.AddText(text1);
            paragraph.AddTab();
            paragraph.AddText(text2);
            paragraph.AddTab();
            paragraph.AddText(text3);
            return paragraph;
        }
    }
}

BonaForMe/BonaForMe.UI/Controllers/CategoryController.cs
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.CategoryService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;

namespace BonaForMe.UI.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(CategoryDto categoryDto)
        {
            try
            {
                var result = _categoryService.AddCategory(categoryDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(CategoryDto categoryDto)
        {
            try
            {
                var result = _categoryService.UpdateCategory(categoryDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            try
            {
                var result = _categoryService.DeleteCategory(id);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult GetCategoryById(Guid id)
        {
            try
            {
                var result = _categoryService.GetCategoryById(id);
                if (result != null)
                {
                    return new JsonResult(result.Data);
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllCategory()
        {
            try
            {
                var result = _categoryService.GetAllCategory();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult LoadCategoryData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                //Paging Size (10,20,50,100)
                int pageSize = Convert.ToInt32(length) != -1 ? Convert.ToInt32(length) : 100;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                DataTableDto dataTable = new DataTableDto()
                {
                    Draw = draw,
                    PageSize = pageSize,
                    Skip = skip,
                    SearchValue = searchValue,
                    SortColumnDirection = sortColumnDirection,
                    SortColumn = sortColumn
                };
                return _categoryService.FillDataTable(dataTable);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

BonaForMe/BonaForMe.UI/Controllers/UserController.cs
using BonaForMe.DomainCommonCore.Helper;
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.UserService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BonaForMe.UI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(UserDto userDto)
        {
            try
            {
                if (userDto == null)
                    return Json(new { success = false });

                if (!userDto.UserMail.Contains("@") && !userDto.UserMail.Contains(".com"))
                    return Json(new { success = false, message = "Please enter a valid email address" });

                if (userDto.Id == Guid.Empty)
                {
                    var mailCheck = _userService.GetUserByEmail(userDto.UserMail);
                    if (mailCheck.Data != null)
                        return Json(new { success = false, message = "The entered e-mail address is registered in the system with another user." });
                }

                if (userDto.Id == Guid.Empty)
                    userDto.UserPassword = PasswordHelper.PasswordEncoder(userDto.UserPassword);
                var result = _userService.AddUser(userDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(UserDto userDto)
        {
            try
            {
                var result = _userService.UpdateUser(userDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            try
            {
                var result = _userService.DeleteUser(id);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult GetUserById(Guid id)
        {
            try
            {
                var result = _userService.GetUserById(id);
                if (result != null)
                {
                    return new JsonResult(result.Data);
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllUser()
        {
            try
            {
                var result = _userService.GetAllUser();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult LoadUserData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                //Paging Size (10,20,50,100)
                int pageSize = Convert.ToInt32(length) != -1 ? Convert.ToInt32(length) : 100;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                DataTableDto dataTable = new DataTableDto()
                {
                    Draw = draw,
                    PageSize = pageSize,
                    Skip = skip,
                    SearchValue = searchValue,
                    SortColumnDirection = sortColumnDirection,
                    SortColumn = sortColumn
                };
                return _userService.FillDataTable(dataTable);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllCustomer()
        {
            try
            {
                var result = _userService.GetAllCustomer();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

BonaForMe/BonaForMe.UI/Views/Shared/_AdminLTE.cshtml
<!DOCTYPE html>
<html>
<head>
    @await Html.PartialAsync("_head")
    @RenderSection("HeadSection", required: false)
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        @await Html.PartialAsync("_Header")
        @await Html.PartialAsync("_Sidebar")

        @RenderBody()

        @await Html.PartialAsync("_Footer")

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    @RenderSection("modal", required: false)
    <div class="modal fade" id="loadMe" tabindex="-1" role="dialog" aria-labelledby="loadMeLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="loader"></div>

                </div>
            </div>
        </div>
    </div>
    <!-- ./wrapper -->
    <!-- Bootstrap 4 -->

    @RenderSection("JsSection", required: false)


    @await Html.PartialAsync("_scripts")

    @if (ViewBag.JavaScriptFunction != null)
    {
        <script type="text/javascript">
            @Html.Raw(ViewBag.JavaScriptFunction)
        </script>
    }

<script type="text/javascript">
        $(document).ready(function () {
            @if (TempData.ContainsKey("Success")) {

                @:ShowMessage('İşlem Başarılı!', 'İşlem Durumu', true);

                 foreach (var key in TempData.Keys.ToList())
                {
                    TempData.Remove(key);
                }
            }
            else if (TempData.ContainsKey("Fail"))
            {
                @:ShowMessage('@TempData["Fail"].ToString()', 'İşlem Durumu', false);

                foreach (var key in TempData.Keys.ToList())
                {
                    TempData.Remove(key);
                }
            };

        });
</script>
</body>
</html>

BonaForMe/BonaForMe.UI/Views/Shared/_Delete.cshtml
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title custom_align" id="HeadingDelete"></h4>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" data-dismiss="modal" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="callout callout-danger">
                    <p>
                        Do you want to delete the selected data?
                    </p>
                </div>
            </div>
            <div class="modal-footer ">
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>Cancel</button>
                <button type="button" class="btn btn-outline-danger" onclick="Delete()"><i class="fa fa-trash"></i>&nbsp;&nbsp;Yes</button>
            </div>
        </div>
    </div>
</div>

BonaForMe/BonaForMe.UI/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<footer class="main-footer">
    @*<div class="pull-right hidden-xs">
        <b>Sürüm</b> 1.0.0
    </div>*@
    <strong>Copyright &copy; @DateTime.UtcNow.AddHours(1).Year <a href="http://bonaforme.com">Boname Marketing </a></strong> All rights reserved.
</footer>

BonaForMe/BonaForMe.UI/Views/Shared/_Header.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" onclick="return ShowResetPasswordModal();" class="dropdown-item">
                    <i class="fas fa-key mr-2"></i> Reset Password
                </a>
                <a href="@Url.Action("Logout","Account")" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i> Log Out
                </a>
                <div class="dropdown-divider"></div>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->
@await Html.PartialAsync("_ResetPassword")

<script>
    function ShowResetPasswordModal(id) {
        $('#resetPasswordModal').modal('show');
    }

    function jsResetPassword() {
        if ($("#NewPassword").val() != $("#VerificationNewPassword").val()) {
            toastr.error("Verification New Password is wrong!");
            return;
        }
        var data = {
            OldPassword: $("#OldPassword").val(),
            NewPassword: $("#NewPassword").val(),
            VerificationNewPassword: $("#VerificationNewPassword").val(),
        };

        var result = ajaxRequest('POST', '@Url.Action("ResetPassword", "Account")', data)
        if (result != null) {
            if (result.success) {
                $('#resetPasswordModal').modal('hide');
                toastr.success('Transaction successful.');
            } else {
                toastr.error(result.message);
            }
        } else {
            $('#resetPasswordModal').modal('hide');
            toastr.error('Error in saving!');
        }
    }
</script>

BonaForMe/BonaForMe.UI/Views/Shared/_Sidebar.cshtml
@{
    var user = BonaForMe.DomainCommonCore.CustomClass.CurrentUser.Get(User);
}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="@Url.Action("Dashboard","Admin")" class="brand-link">
        <img src="~/images/bonameformelogo.jpg" alt="logo" class="brand-image img-circle elevation-3" style="opacity: .8" width="50" height="50">
        <span class="brand-text font-weight-light">BONAME</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/images/user.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@user.UserName</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Menus</li>
                <li class="nav-item">
                    <a href="@Url.Action("Dashboard","Admin")" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","User")" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            User
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Announcement")" class="nav-link">
                        <i class="nav-icon fas fa-bullhorn"></i>
                        <p>
                            Announcements
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Category")" class="nav-link">
                        <i class="nav-icon fas fa-tasks"></i>
                        <p>
                            Categories
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","ContactInformation")" class="nav-link">
                        <i class="nav-icon fas fa-id-card"></i>
                        <p>
                            Contact Informations
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","CurrencyUnit")" class="nav-link">
                        <i class="nav-icon fas fa-money-check"></i>
                        <p>
                            Currency Units
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Order")" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Orders
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("InvoiceList","Order")" class="nav-link">
                        <i class="nav-icon fas fa-file-archive"></i>
                        <p>
                            Invoices
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","OrderStatus")" class="nav-link">
                        <i class="nav-icon fas fa-sort"></i>
                        <p>
                            Order Statuses
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","PaymentInfo")" class="nav-link">
                        <i class="nav-icon fas fa-credit-card"></i>
                        <p>
                            Payment Infos
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","Product")" class="nav-link">
                        <i class="nav-icon fas fa-cube"></i>
                        <p>
                            Products
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","ProductUnit")" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            Product Units
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","CampaignProduct")" class="nav-link">
                        <i class="nav-icon fas fa-fire"></i>
                        <p>
                            Campaign Products
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","SpecialPrice")" class="nav-link">
                        <i class="nav-icon fas fa-street-view"></i>
                        <p>
                            Special Price
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","OrderHour")" class="nav-link">
                        <i class="nav-icon fas fa-clock"></i>
                        <p>
                            Order Hours
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","WorkPartner")" class="nav-link">
                        <i class="nav-icon fas fa-handshake"></i>
                        <p>
                            Work Partners
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Index","ApplicationSetting")" class="nav-link">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            Application Settings
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("CourierTracking","Home")" class="nav-link">
                        <i class="nav-icon fas fa-motorcycle"></i>
                        <p>
                            Courier Follow
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Reports","Admin")" class="nav-link">
                        <i class="nav-icon fas fa-file"></i>
                        <p>
                            Reports
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>