BonaForMe/BonaForMe.UI/Controllers/ContactInformationController.cs
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.ContactInformationService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;

namespace BonaForMe.UI.Controllers
{
    [Authorize]
    public class ContactInformationController : Controller
    {
        private readonly IContactInformationService _contactInformationService;
        public ContactInformationController(IContactInformationService contactInformationService)
        {
            _contactInformationService = contactInformationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(ContactInformationDto contactInformationDto)
        {
            try
            {
                var result = _contactInformationService.AddContactInformation(contactInformationDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(ContactInformationDto contactInformationDto)
        {
            try
            {
                var result = _contactInformationService.UpdateContactInformation(contactInformationDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            try
            {
                var result = _contactInformationService.DeleteContactInformation(id);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult GetContactInformationById(Guid id)
        {
            try
            {
                var result = _contactInformationService.GetContactInformationById(id);
                if (result != null)
                {
                    return new JsonResult(result.Data);
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllContactInformation()
        {
            try
            {
                var result = _contactInformationService.GetAllContactInformation();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult LoadContactInformationData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                //Paging Size (10,20,50,100)
                int pageSize = Convert.ToInt32(length) != -1 ? Convert.ToInt32(length) : 100;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                DataTableDto dataTable = new DataTableDto()
                {
                    Draw = draw,
                    PageSize = pageSize,
                    Skip = skip,
                    SearchValue = searchValue,
                    SortColumnDirection = sortColumnDirection,
                    SortColumn = sortColumn
                };
                return _contactInformationService.FillDataTable(dataTable);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

BonaForMe/BonaForMe.UI/Views/ContactInformation/Index.cshtml
@model BonaForMe.DomainCore.DTO.ContactInformationDto
@{
    ViewData["Title"] = "Contact Informations";
    ViewData["SingleName"] = "Contact Information";
    Layout = "~/Views/Shared/_AdminLTE.cshtml";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@ViewData["Title"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">@ViewData["Title"]</a></li>
                        <li class="breadcrumb-item active">Index</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">@ViewData["Title"]</h3>
                            <button class="btn-success" onclick="jsOpenSaveContactInformation();" style="padding: 10px; float:right;">
                                <i class="fas fa-save"></i>
                                New @ViewData["SingleName"]
                            </button>
                        </div>
                        <div class="card-body" style="overflow-x:auto;">
                            <table id="tblContactInformationList" class="table table-bordered table-striped table-responsive-lg" style="width: 100% !important;">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Email Info</th>
                                        <th>Whattsapp Phone</th>
                                        <th>Customer Support Phone</th>
                                        <th class="noExport">Actions</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div class="modal fade" id="modalSave" data-keyboard="false" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="modalCaption" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <span id="modalCaption">New @ViewData["SingleName"]</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="EmailInfo" class="control-label"><span style="color:red">* </span>Email Info</label>
                            <input name="EmailInfo" id="EmailInfo" class="form-control" required />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="WhattsappPhone" class="control-label"><span style="color:red">* </span>WhattsappPhone</label>
                            <input name="WhattsappPhone" id="WhattsappPhone" class="form-control" required />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="CustomerSupportPhone" class="control-label"><span style="color:red">* </span>CustomerSupportPhone</label>
                            <input name="CustomerSupportPhone" id="CustomerSupportPhone" class="form-control" required />
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" data-content="remove" class="btn btn-default" data-dismiss="modal"> Cancel </button>
                <button type="submit" class="btn btn-primary" data-dismiss="modal" onclick="jsSaveContactInformation()"> Save </button>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_Delete")
<input type="hidden" id="hdnContactInformationId" value="" />
<div class="spinnerAnimation" style="display:none;"></div>
<link href="~/css/spinner.css" rel="stylesheet" />

@await Html.PartialAsync("_datatableScripts")
<script>
    document.addEventListener("DOMContentLoaded", function () {
        createTable();
    });

    function createTable() {
        var domString = getTableDom();
        var buttons = getTableButtons("ContactInformations");
        $('#tblContactInformationList').DataTable
        ({
            "paging": true,
            "ordering": true,
            "pageLength": 25,
            "processing": true,
            "serverSide": true,
            "filter": true,
            "orderMulti": false,
            "order": [[1, "desc"]],
            dom: domString,
            buttons: buttons,
            "ajax": {
                "url": "/ContactInformation/LoadContactInformationData/",
                "type": 'POST',
                "dataType": "json"
            },
            "columnDefs": [{
                "targets": [0],
                "visible": false,
                "searchable": false
            }],
            "columns": [
                getCell("Id"),
                getCell("EmailInfo"),
                getCell("WhattsappPhone"),
                getCell("CustomerSupportPhone"),
                {
                    "data": "", "name": "", "autoWidth": true, "sorting": false, "style": "text-align:center",
                    "render": function (data, type, full, meta) {
                        var buttonGroup = "<div class='btn-group role='group'>";
                        buttonGroup += "<a href='#' class='btn btn-warning btn-sm' style='color:white; margin:0px 5px;' onclick=jsOpenSaveContactInformation('" + full.id + "');><i class='fas fa-edit'></i> Edit </a>"
                        buttonGroup += "<a href='#' class='btn btn-danger btn-sm' style='color:white; margin:0px 5px;' onclick=DeleteData('" + full.id + "');> <i class='fas fa-trash'></i> Delete </a>";
                        buttonGroup += "</div>"
                        return buttonGroup;
                    }
                },
            ],
            "bDestroy": true,
        });
    }

    function jsOpenSaveContactInformation(id) {
        $("#hdnContactInformationId").val("");
        $("#EmailInfo").val("");
        $("#WhattsappPhone").val("");
        $("#CustomerSupportPhone").val("");

        if (id != null && id !== "") {
            var data = { id: id }
            var result = ajaxRequest('POST', '@Url.Action("GetContactInformationById", "ContactInformation")', data)
            $("#hdnContactInformationId").val(result.id);
            $("#EmailInfo").val(result.emailInfo);
            $("#WhattsappPhone").val(result.whattsappPhone);
            $("#CustomerSupportPhone").val(result.customerSupportPhone);
        }
        $('#modalSave').modal('show');
    }

    function jsSaveContactInformation() {
        var data = {
            Id: $("#hdnContactInformationId").val(),
            EmailInfo: $("#EmailInfo").val(),
            WhattsappPhone: $("#WhattsappPhone").val(),
            CustomerSupportPhone: $("#CustomerSupportPhone").val(),
        };

        var result = ajaxRequest('POST', '@Url.Action("Save", "ContactInformation")', data)
        debugger;
        if (result != null) {
            if (result.success) {
                $('#modalSave').modal('hide');
                thisTable = $('#tblContactInformationList').DataTable();
                thisTable.draw();
                toastr.success('Transaction successful.');
            } else {
                toastr.error(result.message);
            }
        } else {
            $('#modalSave').modal('hide');
            toastr.error('Error in saving!');
        }
    }

    function DeleteData(id) {
        $('#delete').data('argument', id);
        $('#delete').modal('show');
    }

    function Delete() {
        var id = $('#delete').data('argument');
        var data = { id: id }
        var result = ajaxRequest('POST', '@Url.Action("Delete", ViewData["SingleName"])', data);
        if (result.success) {
            $('#delete').modal('hide');
            thisTable = $('#tblContactInformationList').DataTable();
            thisTable.draw();
            toastr.success('The deletion was successful.');
        } else {
            $('#delete').modal('hide');
            toastr.error('Error in deletion!');
        }
    }
</script>