BonaForMe/BonaForMe.UI/Controllers/CampaignProductController.cs
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.CampaignProductService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BonaForMe.UI.Controllers
{
    [Authorize]
    public class CampaignProductController : Controller
    {
        private readonly ICampaignProductService _campaignProductService;
        public CampaignProductController(ICampaignProductService campaignProductService)
        {
            _campaignProductService = campaignProductService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(CampaignProductDto campaignProductDto)
        {
            try
            {
                var result = _campaignProductService.AddCampaignProduct(campaignProductDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(CampaignProductDto campaignProductDto)
        {
            try
            {
                var result = _campaignProductService.UpdateCampaignProduct(campaignProductDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            try
            {
                var result = _campaignProductService.DeleteCampaignProduct(id);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult GetCampaignProductById(Guid id)
        {
            try
            {
                var result = _campaignProductService.GetCampaignProductById(id);
                if (result != null)
                {
                    return new JsonResult(result.Data);
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllCampaignProduct()
        {
            try
            {
                var result = _campaignProductService.GetAllCampaignProduct();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult LoadCampaignProductData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                //Paging Size (10,20,50,100)
                int pageSize = Convert.ToInt32(length) != -1 ? Convert.ToInt32(length) : 100;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                DataTableDto dataTable = new DataTableDto()
                {
                    Draw = draw,
                    PageSize = pageSize,
                    Skip = skip,
                    SearchValue = searchValue,
                    SortColumnDirection = sortColumnDirection,
                    SortColumn = sortColumn
                };
                return _campaignProductService.FillDataTable(dataTable);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

BonaForMe/BonaForMe.UI/Controllers/ProductController.cs
using BonaForMe.DomainCore.DTO;
using BonaForMe.ServiceCore.ProductService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;

namespace BonaForMe.UI.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(ProductDto productDto)
        {
            try
            {
                var result = _productService.AddProduct(productDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(ProductDto productDto)
        {
            try
            {
                var result = _productService.UpdateProduct(productDto);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            try
            {
                var result = _productService.DeleteProduct(id);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult GetProductById(Guid id)
        {
            try
            {
                var result = _productService.GetProductById(id);
                if (result != null)
                {
                    return new JsonResult(result.Data);
                }
                return Json(new { success = false });
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllProduct()
        {
            try
            {
                var result = _productService.GetAllProduct();
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult GetAllProductByCategoryId(Guid id)
        {
            try
            {
                var result = _productService.GetAllProductByCategoryId(id);
                return new JsonResult(result.Data);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult UpdateProductStock(Guid Id, int newStock = 0, int reducedStock = 0)
        {
            try
            {
                var result = _productService.UpdateProductStock(Id, newStock, reducedStock);
                return new JsonResult(result);
            }
            catch (Exception)
            {
                return null;
            }
        }

        [HttpPost]
        public IActionResult LoadProductData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                // Skiping number of Rows count
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();
                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                // Sort Column Direction ( asc ,desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                //Paging Size (10,20,50,100)
                int pageSize = Convert.ToInt32(length) != -1 ? Convert.ToInt32(length) : 100;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                DataTableDto dataTable = new DataTableDto()
                {
                    Draw = draw,
                    PageSize = pageSize,
                    Skip = skip,
                    SearchValue = searchValue,
                    SortColumnDirection = sortColumnDirection,
                    SortColumn = sortColumn
                };
                return _productService.FillDataTable(dataTable);
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

BonaForMe/BonaForMe.UI/Views/CampaignProduct/Index.cshtml
@model BonaForMe.DomainCore.DTO.CampaignProductDto
@{
    ViewData["Title"] = "Campaign Products";
    ViewData["SingleName"] = "Campaign Product";
    Layout = "~/Views/Shared/_AdminLTE.cshtml";
}

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@ViewData["Title"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">@ViewData["Title"]</a></li>
                        <li class="breadcrumb-item active">Index</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">@ViewData["Title"]</h3>
                            <button class="btn-success" onclick="jsOpenSaveCampaignProduct();" style="padding: 10px; float:right;">
                                <i class="fas fa-save"></i>
                                New @ViewData["SingleName"]
                            </button>
                        </div>
                        <div class="card-body" style="overflow-x:auto;">
                            <table id="tblCampaignProductList" class="table table-bordered table-striped table-responsive-lg" style="width: 100% !important;">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Product</th>
                                        <th>Amount</th>
                                        <th>Top Price Limit</th>
                                        <th class="noExport">Actions</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div class="modal fade" id="modalSave" data-keyboard="false" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="modalCaption" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <span id="modalCaption">New @ViewData["SingleName"]</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="ProductId" class="control-label"><span style="color:red">* </span>Product</label>
                            <select id="ProductId" class="form-control select2" name="ProductId" required>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Amount" class="control-label"><span style="color:red">* </span>Amount</label>
                            <input name="Amount" id="Amount" class="form-control" type="number" required />
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="TopPriceLimit" class="control-label"><span style="color:red">* </span>Top Price Limit</label>
                            <input name="TopPriceLimit" id="TopPriceLimit" class="form-control" type="number" required />
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" data-content="remove" class="btn btn-default" data-dismiss="modal"> Cancel </button>
                <button type="submit" class="btn btn-primary" data-dismiss="modal" onclick="jsSaveCampaignProduct()"> Save </button>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_Delete")
<input type="hidden" id="hdnCampaignProductId" value="" />
<div class="spinnerAnimation" style="display:none;"></div>
<link href="~/css/spinner.css" rel="stylesheet" />
<script src="~/adminLTE/plugins/select2/js/select2.full.min.js"></script>

@await Html.PartialAsync("_datatableScripts")
<script>
    document.addEventListener("DOMContentLoaded", function () {
        createTable();
        fillProductSelect();
        $('.select2').select2()
    });

    function createTable() {
        var domString = getTableDom();
        var buttons = getTableButtons("CampaignProducts");
        $('#tblCampaignProductList').DataTable
        ({
            "paging": true,
            "ordering": true,
            "pageLength": 25,
            "processing": true,
            "serverSide": true,
            "filter": true,
            "orderMulti": false,
            "order": [[1, "desc"]],
            dom: domString,
            buttons: buttons,
            "ajax": {
                "url": "/CampaignProduct/LoadCampaignProductData/",
                "type": 'POST',
                "dataType": "json"
            },
            "columnDefs": [{
                "targets": [0],
                "visible": false,
                "searchable": false
            }],
            "columns": [
                getCell("Id"),
                getCell("ProductName"),
                getCell("Amount"),
                getCell("TopPriceLimit"),
                {
                    "data": "", "name": "", "autoWidth": true, "sorting": false, "style": "text-align:center",
                    "render": function (data, type, full, meta) {
                        var buttonGroup = "<div class='btn-group role='group'>";
                        buttonGroup += "<a href='#' class='btn btn-warning btn-sm' style='color:white; margin:0px 5px;' onclick=jsOpenSaveCampaignProduct('" + full.id + "');><i class='fas fa-edit'></i> Edit </a>"
                        buttonGroup += "<a href='#' class='btn btn-danger btn-sm' style='color:white; margin:0px 5px;' onclick=DeleteData('" + full.id + "');> <i class='fas fa-trash'></i> Delete </a>";
                        buttonGroup += "</div>"
                        return buttonGroup;
                    }
                },
            ],
            "bDestroy": true,
        });
    }

    function jsOpenSaveCampaignProduct(id) {
        $("#hdnCampaignProductId").val("");
        $("#ProductId").val("");
        $("#Amount").val("");
        $("#TopPriceLimit").val("");

        if (id != null && id !== "") {
            var data = { id: id }
            var result = ajaxRequest('POST', '@Url.Action("GetCampaignProductById", "CampaignProduct")', data)
            $("#hdnCampaignProductId").val(result.id);
            $("#ProductId").val(result.productId);
            $("#Amount").val(result.amount);
            $("#TopPriceLimit").val(result.topPriceLimit);
        }
        $('#modalSave').modal('show');
    }

    function jsSaveCampaignProduct() {
        var data = {
            Id: $("#hdnCampaignProductId").val(),
            ProductId: $("#ProductId").val(),
            Amount: $("#Amount").val(),
            TopPriceLimit: $("#TopPriceLimit").val(),
        };

        var result = ajaxRequest('POST', '@Url.Action("Save", "CampaignProduct")', data)
        if (result != null) {
            if (result.success) {
                $('#modalSave').modal('hide');
                thisTable = $('#tblCampaignProductList').DataTable();
                thisTable.draw();
                toastr.success('Transaction successful.');
            } else {
                toastr.error(result.message);
            }
        } else {
            $('#modalSave').modal('hide');
            toastr.error('Error in saving!');
        }
    }

    function DeleteData(id) {
        $('#delete').data('argument', id);
        $('#delete').modal('show');
    }

    function Delete() {
        var id = $('#delete').data('argument');
        var data = { id: id }
        var result = ajaxRequest('POST', '@Url.Action("Delete", ViewData["SingleName"])', data);
        if (result.success) {
            $('#delete').modal('hide');
            thisTable = $('#tblCampaignProductList').DataTable();
            thisTable.draw();
            toastr.success('The deletion was successful.');
        } else {
            $('#delete').modal('hide');
            toastr.error('Error in deletion!');
        }
    }

    function fillProductSelect() {
        var result = ajaxRequest('POST', '@Url.Action("GetAllProduct", "Product")')
        fillOptions("ProductId", result, "name");
    }
</script>